name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # Changeable region
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      project: DiplomWebApi 
    # Endregion
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    # Add this step to install .NET Aspire workload
    - name: Install .NET Aspire workload
      run: |
        dotnet workload install aspire
        dotnet workload restore
        

    - name: Restore dependencies
      run: dotnet restore /p:Configuration=${{ matrix.configuration }}
    
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
    
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }} (${{ matrix.configuration }})
        path: ${{ env.project }}/bin/${{ matrix.configuration }} 

